project_id = "pnqkollfbuqlrqvodrpt"

[functions.processar-qr-scan]
verify_jwt = false

[functions.gerar-qr-code]
verify_jwt = false

[functions.qr-update-etapa]
verify_jwt = false

[functions.criar-usuario]
verify_jwt = true
